export const metadata = {
  title: "Privacy Policy — SolarDesign",
}

export default function PrivacyPage() {
  return (
    <section className="mx-auto w-full max-w-3xl px-6 py-16">
      <h1 className="mb-2 text-3xl font-bold tracking-tight">Privacy Policy</h1>
      <p className="mb-10 text-sm text-muted-foreground">
        Effective date: 18 April 2026 · Last updated: 18 April 2026
      </p>

      <div className="prose prose-sm max-w-none text-foreground [&_a]:underline [&_a]:underline-offset-2 [&_a:hover]:text-muted-foreground [&_h2]:mt-10 [&_h2]:mb-3 [&_h2]:text-lg [&_h2]:font-semibold [&_h3]:mt-6 [&_h3]:mb-2 [&_h3]:font-semibold [&_p]:mb-4 [&_p]:text-muted-foreground [&_ul]:mb-4 [&_ul]:ml-5 [&_ul]:list-disc [&_ul]:text-muted-foreground [&_li]:mb-1">

        <p>
          This Privacy Policy describes how SolarDesign (&ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;) collects,
          uses, stores, and processes personal data in connection with the SolarDesign platform
          (&ldquo;Platform&rdquo;). It applies to all users who access the Platform, including design engineers,
          EPC contractors, IPPs, and solar consultants.
        </p>
        <p>
          This Policy is governed by the Digital Personal Data Protection Act, 2023 (&ldquo;DPDP Act&rdquo;),
          the Information Technology Act, 2000 (&ldquo;IT Act&rdquo;), and the Information Technology
          (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information)
          Rules, 2011 (&ldquo;SPDI Rules&rdquo;).
        </p>

        <h2>1. Data Fiduciary</h2>
        <p>
          SolarDesign is the Data Fiduciary as defined under the DPDP Act. We determine the purpose
          and means of processing personal data collected through the Platform.
        </p>
        <p>
          Registered office: Bengaluru, Karnataka, India.<br />
          Contact: <a href="mailto:privacy@solardesign.in">privacy@solardesign.in</a>
        </p>

        <h2>2. Personal Data We Collect</h2>
        <h3>Account and identity data</h3>
        <ul>
          <li>Name, work email address, phone number</li>
          <li>Organisation name, designation, and GST registration number (for invoicing)</li>
          <li>Login credentials (password stored as a salted hash; never in plain text)</li>
        </ul>
        <h3>Project and design data</h3>
        <ul>
          <li>KMZ / KML / DXF files uploaded by the user</li>
          <li>Project configurations, layout parameters, simulation inputs and outputs</li>
          <li>SLD, cable schedules, BoM, BoQ, and DPR files generated by the Platform</li>
          <li>Version history and design annotations</li>
        </ul>
        <h3>Usage and technical data</h3>
        <ul>
          <li>IP address, browser type, operating system</li>
          <li>Pages visited, features accessed, session duration</li>
          <li>Error logs and diagnostic data</li>
        </ul>
        <h3>Billing data</h3>
        <ul>
          <li>Invoice details, payment method type (we do not store full card numbers)</li>
          <li>GST number and billing address for INR invoice generation</li>
        </ul>

        <h2>3. Purpose of Processing</h2>
        <p>We process personal data for the following purposes:</p>
        <ul>
          <li>Providing and operating the Platform, including authentication and project management</li>
          <li>Running energy simulations using third-party irradiance data sources (Meteonorm, NASA POWER, Solargis)</li>
          <li>Generating SLD, cable schedules, ALMM-compliant equipment reports, BoM, BoQ, and DPR exports</li>
          <li>Processing subscription payments and issuing GST-compliant INR invoices</li>
          <li>Sending transactional communications: account activation, password reset, subscription renewal</li>
          <li>Product updates and feature announcements (opt-out available at any time)</li>
          <li>Security monitoring, fraud detection, and platform integrity</li>
          <li>Compliance with applicable Indian law</li>
        </ul>
        <p>
          We do not sell, rent, or trade personal data to third parties for marketing purposes.
        </p>

        <h2>4. Legal Basis for Processing</h2>
        <ul>
          <li><strong>Consent:</strong> Provided at account creation and for optional communications. Consent may be withdrawn at any time without affecting prior processing.</li>
          <li><strong>Contractual necessity:</strong> Processing required to deliver the Platform under the Terms of Service.</li>
          <li><strong>Legal obligation:</strong> Processing required to comply with Indian tax law, GST regulations, and regulatory requirements applicable to the Platform.</li>
          <li><strong>Legitimate interests:</strong> Security monitoring and platform improvement, subject to Data Principal rights.</li>
        </ul>

        <h2>5. Third-Party Data Processors</h2>
        <p>
          We engage the following categories of processors, each bound by data processing agreements:
        </p>
        <ul>
          <li><strong>Cloud infrastructure:</strong> Servers located in India or within jurisdictions approved under the DPDP Act for cross-border transfer</li>
          <li><strong>Irradiance data providers:</strong> Meteonorm (Switzerland), NASA POWER (USA), Solargis (Slovakia) — project coordinates are transmitted to retrieve TMY data; no personal identity data is shared</li>
          <li><strong>Payment processor:</strong> For subscription billing; PCI-DSS compliant</li>
          <li><strong>Email delivery:</strong> For transactional notifications only</li>
        </ul>

        <h2>6. Data Retention</h2>
        <ul>
          <li>Account data: retained for the duration of the subscription and for 3 years after account closure, unless a shorter period is required by law</li>
          <li>Project and design data: retained for the duration of the subscription; deleted within 90 days of account closure on written request</li>
          <li>Billing records: retained for 8 years as required under the GST Act and Income Tax Act</li>
          <li>Server logs: retained for 180 days</li>
        </ul>

        <h2>7. Rights of the Data Principal</h2>
        <p>
          Under the DPDP Act, 2023, you have the following rights with respect to your personal data:
        </p>
        <ul>
          <li><strong>Right to access:</strong> Obtain a summary of personal data held and the processing activities carried out</li>
          <li><strong>Right to correction and erasure:</strong> Correct inaccurate or incomplete data; request erasure where retention is no longer necessary</li>
          <li><strong>Right to grievance redressal:</strong> File a grievance with our Grievance Officer (see Section 10)</li>
          <li><strong>Right to nominate:</strong> Nominate another individual to exercise rights in the event of death or incapacity</li>
          <li><strong>Right to withdraw consent:</strong> Withdraw consent for processing at any time; withdrawal does not affect prior processing</li>
        </ul>
        <p>
          Requests under this section may be submitted to{" "}
          <a href="mailto:privacy@solardesign.in">privacy@solardesign.in</a>. We will respond
          within 30 days.
        </p>

        <h2>8. Security</h2>
        <p>
          We implement security practices consistent with the SPDI Rules, 2011, including:
        </p>
        <ul>
          <li>Encryption of data in transit (TLS 1.2 or higher) and at rest (AES-256)</li>
          <li>Role-based access controls limiting data access to authorised personnel</li>
          <li>Regular security assessments and penetration testing</li>
          <li>Incident response procedures with mandatory notification timelines</li>
        </ul>
        <p>
          In the event of a personal data breach that is likely to affect your rights, we will notify
          you and the Data Protection Board of India as required under the DPDP Act.
        </p>

        <h2>9. Cookies and Tracking</h2>
        <p>
          We use strictly necessary cookies for session management and authentication. Analytics
          cookies are used only with your consent. You may manage cookie preferences through your
          browser settings. Disabling strictly necessary cookies will prevent you from logging in.
        </p>

        <h2>10. Grievance Officer</h2>
        <p>
          As required under Section 5(9) of the SPDI Rules, 2011 and the DPDP Act, 2023, we have
          designated a Grievance Officer:
        </p>
        <ul>
          <li><strong>Name:</strong> Grievance Officer, SolarDesign</li>
          <li><strong>Email:</strong> <a href="mailto:grievance@solardesign.in">grievance@solardesign.in</a></li>
          <li><strong>Response time:</strong> Acknowledgement within 5 business days; resolution within 30 days</li>
        </ul>
        <p>
          If your grievance is not resolved to your satisfaction, you may approach the Data Protection
          Board of India established under the DPDP Act.
        </p>

        <h2>11. Changes to This Policy</h2>
        <p>
          We may update this Policy to reflect changes in the Platform, applicable law, or our
          processing practices. Material changes will be notified by email to the registered account
          address at least 14 days before they take effect. Continued use of the Platform after the
          effective date constitutes acceptance of the updated Policy.
        </p>

        <h2>12. Contact</h2>
        <p>
          For privacy-related queries not covered by the grievance process:{" "}
          <a href="mailto:privacy@solardesign.in">privacy@solardesign.in</a>
        </p>
      </div>
    </section>
  )
}
