/**
 * Prisma extension that prevents manual ID injection.
 * Removes any manually-provided 'id' field from create/createMany/upsert
 * and logs a warning. All IDs must be generated by semanticIdExtension.
 *
 * Applied BEFORE semanticIdExtension in the $extends chain so that
 * manually-provided IDs are stripped before generation runs.
 */
export const strictIdExtension = {
  name: "mvp-id-enforcement",
  query: {
    $allModels: {
      async create({
        args,
        model,
        query,
      }: {
        args: any
        model: string
        query: any
      }) {
        if (args.data?.id) {
          console.warn(
            `[ID-ENFORCEMENT] Manual ID provided for ${model} create — using semantic ID instead`
          )
          delete args.data.id
        }
        return query(args)
      },

      async createMany({
        args,
        model,
        query,
      }: {
        args: any
        model: string
        query: any
      }) {
        if (args.data && Array.isArray(args.data)) {
          args.data = args.data.map((item: any) => {
            if (item.id) {
              console.warn(
                `[ID-ENFORCEMENT] Manual ID provided for ${model} createMany — using semantic ID instead`
              )
              const { id, ...rest } = item
              return rest
            }
            return item
          })
        }
        return query(args)
      },

      async upsert({
        args,
        model,
        query,
      }: {
        args: any
        model: string
        query: any
      }) {
        if (args.create?.id) {
          console.warn(
            `[ID-ENFORCEMENT] Manual ID provided for ${model} upsert.create — using semantic ID instead`
          )
          delete args.create.id
        }
        return query(args)
      },
    },
  },
} as const
